[package]
name = "RaytracerMatrixBased"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.20.5"
image = "0.24.2"
rayon = "1.5.3"
num_cpus = "1.13.1"
rand = "0.8.5"
